#These are some new aliases I am going to work with in bash. These are my own. 
alias c='clear'
alias e='exit'
alias a='atom'
alias v='vim'
alias projects='cd ~/Github_Projects/'
alias myapp='cd ~/Github_Projects/PAPA'
alias ..='cd ../'
alias ...='cd ../../'
alias downloads='cd ~/Downloads'
alias hello='echo "Hello World!"'
alias upgrade='sudo apt update && sudo apt upgrade'
alias jup='jupyter notebook'
alias iceweasel='firefox&'
#alias python='/usr/bin/python3'
