[window]
decorations = "None"
startup_mode = "Fullscreen"
padding = { x = 4, y = 2}
dynamic_padding = true

[font]
size = 13
normal = { family = "Hack Nerd Font", style = "Regular"}

[selection]
save_to_clipboard = true

